name: Nightly Full Test Suite

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  nightly-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Run type checking
      run: npm run type-check
      
    - name: Run unit tests
      run: npm run test:unit
      
    - name: Run domain scope regression tests
      run: npm run test:regression
      
    - name: Run smoke tests
      run: npm run test:smoke
      
    - name: Run full test suite
      run: npm run test:full -- --runInBand
      
    - name: Run coverage analysis
      run: npm run coverage:threshold
      
    - name: Check for dead code
      run: npm run dead-code
      
    - name: Validate API contract
      run: npm run validate-api-contract
      
    - name: Check legacy documentation
      run: npm run check-legacy-docs
      
    - name: Check legacy frontend
      run: npm run check-legacy-frontend
      
    - name: Check workflow replay guardrails
      run: npm run check-workflowreplay-guardrails
      
    - name: Check variable config modal guardrails
      run: npm run check-variableconfigmodal-guardrails
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-node-${{ matrix.node-version }}
        path: |
          coverage/
          test-results/
          
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚨 Nightly test suite failed! Please check the workflow run for details.'
          })
